version: '3.8'
services:
  db:
    image: postgres:13
    container_name: zverev_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: zverev_app
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  postgres_data:
